version: '2'
checks:
  file-lines:
    enabled: false
    config:
      threshold: 250
  method-lines:
    enabled: true
    config:
      threshold: 60
  similar-code:
    enabled: true
    config:
      threshold: 70
  identical-code:
    enabled: true
    config:
      threshold: 70
  duplication:
    enabled: true
exclude_patterns:
  - 'scripts/'
  - 'apps/'
  - 'api-specifications/'
  - 'core/'
  - '**/mocks/'
  - '**/theme/'
  - '**/icons/'
  - '**/*.d.ts'
  - '**/__tests__/'
  - '**/node_modules'
