name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: Check typing
        run: yarn types:check
      - name: Check lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: Check build
        run: yarn build
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: sn-container-ext
          path: sn-container-ext

  publish-dev:
    needs: [validate, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: sn-container-ext
          path: ./sn-container-ext
      - name: Create extension
        run: zip -r "sn-container-ext.zip" "./sn-container-ext"
