name: Part - Lint

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      npmencoded:
        required: true

jobs:
  ci-run-container-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - uses: actions/setup-node@v3
        with:
          node-version: 17.2.0
          cache: 'npm'

      - name: Run yarn
        run: yarn
      - name: Run lint
        run: yarn lint
