name: publish

on:
  workflow_run:
    workflows: [Validate, Test]
    branches: [main]
    types:
      - completed

jobs:
  publish-dev:
    needs: [build, test-unit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - run: yarn --frozen-lockfile
      - name:
        run: zip -r "sn-container-ext.zip" "./sn-container-ext"
