name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - run: yarn --frozen-lockfile
      - name: Run unit tests and publish results to CodeClimate
        timeout-minutes: 10
        run: yarn test:unit
